services:
  mysql:
    image: mysql:8.4
    container_name: stocks-mysql
    environment:
      MYSQL_USER: unwire
      MYSQL_PASSWORD: unwire
      MYSQL_ROOT_PASSWORD: unwire
      MYSQL_DATABASE: stocks
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
